name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ftp.dslab.digitalscholar.rochester.edu
        user: jeasterly@dslab.digitalscholar.rochester.edu
        password: pcn2BXW@nvc.yku2hze
        localDir: "."
        remoteDir: "public_html/public-art/themes/default"
        options: "--delete --asci"
